piro12/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home),
    path('article', views.articlelist, name='articlelist'),
    path('article/<int:pk>', views.articledetail, name='articledetail'),
    path('articlecreate', views.articlecreate, name='articlecreate'),
]

piro12/piro12/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

piro12/core/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    author = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

piro12/core/views.py
from django.shortcuts import render,reverse
from .models import Article
# Create your views here.

def home(request):
    return render(request, 'base.html')

def articlelist(request):
    articles = Article.objects.all()
    ctx = {
        'articles': articles
    }
    return render(request,'core/listarticle.html', ctx)

def articledetail(request, pk):
    article = Article.objects.get(pk=pk)
    ctx = {
        'article': article
    }
    return render(request,'core/articledetail.html', ctx)


def articlecreate(request):
    if request.method == "POST":
        title = request.POST['title']
        author = request.POST['author']
        content = request.POST['content']
        article = Article.objects.create(title=title,author=author,content=content)
        ctx = {
            'article': article
        }
        return render(request,'core/articledetail.html', ctx)
    return render(request, 'core/articlecreate.html')

piro12/core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3>안녕하세요 손준혁입니다.</h3>
</body>
</html>

piro12/core/templates/core/articlecreate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <label>제목</label>
        <input name="title">
        <label>내용</label>
        <input name="content">
        <label>저자</label>
        <input name="author">
        <button type="submit">제출</button>
    </form>
</body>
</html>

piro12/core/templates/core/articledetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div style="width: 500px;margin: auto;">
        <h1>{{ article.title }}</h1>
        <br/>
        <p>
            <span>{{ article.author }}  </span>
            <span>{{ article.created_at}}</span>
        </p>
        <h3>{{ article.content }}</h3>
        <p><a href="{% url 'core:articlelist' %}">리스트</a></p>
    </div>
</body>
</html>

piro12/core/templates/core/listarticle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div style="width: 400px;margin: auto">
        <h3>리스트입니다<h3>
            <div>
                {% for article in articles %}
                <div>
                    <p>제목 :
                        <a href="{% url 'core:articledetail' article.pk %}">
                        {{ article }}</a>
                    </p>


                </div>

                {% endfor %}
            </div>
    </div>
</body>
</html>